// <auto-generated />
using System;
using IntelliFit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Presistence.Migrations
{
    [DbContext(typeof(IntelliFitDbContext))]
    [Migration("20251212205141_AddFirstLoginFlags")]
    partial class AddFirstLoginFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending", "confirmed", "cancelled", "completed", "no_show" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "equipment_status", new[] { "available", "in_use", "under_maintenance", "out_of_service", "reserved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gender_type", new[] { "male", "female" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "booking_reminder", "maintenance_alert", "payment_due", "workout_complete", "milestone_achieved", "coach_message", "system_alert", "promotional_offer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "pending", "completed", "failed", "refunded", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_status", new[] { "active", "expired", "cancelled", "suspended", "pending_payment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", new[] { "purchase", "deduction", "refund", "bonus", "earned" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntelliFit.Domain.Models.ActivityFeed", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("activity_feeds", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AiChatLog", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatId"));

                    b.Property<string>("AiModel")
                        .HasColumnType("text");

                    b.Property<string>("ContextData")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ChatId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "SessionId");

                    b.ToTable("ai_chat_logs", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AiProgramGeneration", b =>
                {
                    b.Property<int>("GenerationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenerationId"));

                    b.Property<string>("AiModel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedPlan")
                        .HasColumnType("text");

                    b.Property<int?>("GenerationTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("InputPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NutritionPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<string>("UserContext")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("integer");

                    b.HasKey("GenerationId");

                    b.HasIndex("NutritionPlanId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("ai_program_generations", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AiWorkflowJob", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("N8nWorkflowId")
                        .HasColumnType("text");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("ai_workflow_jobs", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<int?>("RecordId")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TokensCost")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("BookingId");

                    b.HasIndex("Status");

                    b.HasIndex("CoachId", "StartTime");

                    b.HasIndex("EquipmentId", "StartTime");

                    b.HasIndex("UserId", "StartTime");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatMessageId"));

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("SenderId", "ReceiverId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.CoachProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailabilitySchedule")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string[]>("Certifications")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.Property<int>("TotalClients")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("coach_profiles", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.CoachReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId");

                    b.HasIndex("Rating");

                    b.HasIndex("UserId");

                    b.HasIndex("CoachId", "CreatedAt");

                    b.ToTable("coach_reviews", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("BookingCostTokens")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConditionRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<int?>("MaxBookingDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EquipmentId");

                    b.HasIndex("CategoryId");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("equipment_categories", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseId"));

                    b.Property<int?>("CaloriesPerMinute")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByCoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentRequired")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("ExerciseId");

                    b.HasIndex("CreatedByCoachId");

                    b.HasIndex("DifficultyLevel");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("Name");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.InBodyMeasurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurementId"));

                    b.Property<int?>("Bmr")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("BodyType")
                        .HasColumnType("text");

                    b.Property<decimal?>("BodyWaterPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("BoneMass")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("MeasuredBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MetabolicAge")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MuscleMass")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProteinPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VisceralFatLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("MeasurementId");

                    b.HasIndex("MeasuredBy");

                    b.HasIndex("UserId");

                    b.ToTable("inbody_measurements", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("integer");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<decimal>("FatsPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("IngredientId");

                    b.HasIndex("Name");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealId"));

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByCoachId")
                        .HasColumnType("integer");

                    b.Property<int>("FatsGrams")
                        .HasColumnType("integer");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NutritionPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("ProteinGrams")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("RecommendedTime")
                        .HasColumnType("interval");

                    b.HasKey("MealId");

                    b.HasIndex("CreatedByCoachId");

                    b.HasIndex("NutritionPlanId");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.MealIngredient", b =>
                {
                    b.Property<int>("MealIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealIngredientId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("MealIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("meal_ingredients", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.MemberProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("FitnessGoal")
                        .HasColumnType("text");

                    b.Property<string>("FitnessLevel")
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MembershipStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredWorkoutTime")
                        .HasColumnType("text");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("TotalCaloriesBurned")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWorkoutsCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PushSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text");

                    b.Property<string[]>("SentVia")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("SmsSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.NutritionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("AiPrompt")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByCoachId")
                        .HasColumnType("integer");

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string[]>("DietaryRestrictions")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FatsGrams")
                        .HasColumnType("integer");

                    b.Property<int?>("GeneratedByCoachId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProteinGrams")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensSpent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId");

                    b.HasIndex("ApprovedByCoachId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GeneratedByCoachId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("nutrition_plans", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("text");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentGateway")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("PackageId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.ProgressMilestone", b =>
                {
                    b.Property<int>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MilestoneId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MilestoneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsReward")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("integer");

                    b.HasKey("MilestoneId");

                    b.ToTable("progress_milestones", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxBookingsPerDay")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TokensIncluded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlanId");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.TokenPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageId"));

                    b.Property<int>("BonusTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TokenAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PackageId");

                    b.ToTable("token_packages", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.TokenTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("token_transactions", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Member");

                    b.Property<int>("TokenBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("LastLoginAt");

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.UserMilestone", b =>
                {
                    b.Property<int>("UserMilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserMilestoneId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MilestoneId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserMilestoneId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("UserId", "MilestoneId");

                    b.ToTable("user_milestones", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.UserSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<bool>("RenewalReminderSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("EndDate");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExercisesCompleted")
                        .HasColumnType("text");

                    b.Property<int?>("FeelingRating")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LogId");

                    b.HasIndex("PlanId");

                    b.HasIndex("WorkoutDate");

                    b.HasIndex("UserId", "WorkoutDate");

                    b.ToTable("workout_logs", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("AiPrompt")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<int?>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exercises")
                        .HasColumnType("text");

                    b.Property<int?>("GeneratedByCoachId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensSpent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GeneratedByCoachId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("workout_plans", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("WorkoutPlanExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkoutPlanExerciseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutPlanExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("workout_plan_exercises", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByCoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("integer");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedByCoachId");

                    b.ToTable("workout_templates", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutTemplateExercise", b =>
                {
                    b.Property<int>("TemplateExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateExerciseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("TemplateExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateId");

                    b.ToTable("workout_template_exercises", (string)null);
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.ActivityFeed", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("ActivityFeeds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AiChatLog", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("AiChatLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AiProgramGeneration", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.NutritionPlan", "NutritionPlan")
                        .WithMany("AiGenerations")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("AiProgramGenerations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("AiGenerations")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NutritionPlan");

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AiWorkflowJob", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("AiWorkflowJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.AuditLog", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Booking", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "Coach")
                        .WithMany("Bookings")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntelliFit.Domain.Models.Equipment", "Equipment")
                        .WithMany("Bookings")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.ChatMessage", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.CoachProfile", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithOne("CoachProfile")
                        .HasForeignKey("IntelliFit.Domain.Models.CoachProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.CoachReview", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "Coach")
                        .WithMany("Reviews")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("CoachReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Equipment", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.EquipmentCategory", "Category")
                        .WithMany("Equipment")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Exercise", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "CreatedByCoach")
                        .WithMany("ExercisesCreated")
                        .HasForeignKey("CreatedByCoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByCoach");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.InBodyMeasurement", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "MeasuredByUser")
                        .WithMany()
                        .HasForeignKey("MeasuredBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("InBodyMeasurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasuredByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Meal", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "CreatedByCoach")
                        .WithMany("MealsCreated")
                        .HasForeignKey("CreatedByCoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByCoach");

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.MealIngredient", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.MemberProfile", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithOne("MemberProfile")
                        .HasForeignKey("IntelliFit.Domain.Models.MemberProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Notification", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.NutritionPlan", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "ApprovedByCoach")
                        .WithMany("NutritionPlansApproved")
                        .HasForeignKey("ApprovedByCoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "GeneratedByCoach")
                        .WithMany("NutritionPlansCreated")
                        .HasForeignKey("GeneratedByCoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByCoach");

                    b.Navigation("GeneratedByCoach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Payment", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.TokenPackage", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.TokenTransaction", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("TokenTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.UserMilestone", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.ProgressMilestone", "Milestone")
                        .WithMany("UserMilestones")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("UserMilestones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.UserSubscription", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntelliFit.Domain.Models.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutLog", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.WorkoutPlan", "Plan")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutPlan", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "ApprovedByCoach")
                        .WithMany("WorkoutPlansApproved")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "Coach")
                        .WithMany("WorkoutPlansCreated")
                        .HasForeignKey("GeneratedByCoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliFit.Domain.Models.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByCoach");

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutPlanExercise", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.Exercise", "Exercise")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutTemplate", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.CoachProfile", "CreatedByCoach")
                        .WithMany("WorkoutTemplatesCreated")
                        .HasForeignKey("CreatedByCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByCoach");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("IntelliFit.Domain.Models.Exercise", "Exercise")
                        .WithMany("WorkoutTemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliFit.Domain.Models.WorkoutTemplate", "Template")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.CoachProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ExercisesCreated");

                    b.Navigation("MealsCreated");

                    b.Navigation("NutritionPlansApproved");

                    b.Navigation("NutritionPlansCreated");

                    b.Navigation("Reviews");

                    b.Navigation("WorkoutPlansApproved");

                    b.Navigation("WorkoutPlansCreated");

                    b.Navigation("WorkoutTemplatesCreated");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Equipment", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutPlanExercises");

                    b.Navigation("WorkoutTemplateExercises");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.NutritionPlan", b =>
                {
                    b.Navigation("AiGenerations");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.ProgressMilestone", b =>
                {
                    b.Navigation("UserMilestones");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.TokenPackage", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.User", b =>
                {
                    b.Navigation("ActivityFeeds");

                    b.Navigation("AiChatLogs");

                    b.Navigation("AiProgramGenerations");

                    b.Navigation("AiWorkflowJobs");

                    b.Navigation("Bookings");

                    b.Navigation("CoachProfile");

                    b.Navigation("CoachReviews");

                    b.Navigation("InBodyMeasurements");

                    b.Navigation("MemberProfile");

                    b.Navigation("Notifications");

                    b.Navigation("NutritionPlans");

                    b.Navigation("Payments");

                    b.Navigation("TokenTransactions");

                    b.Navigation("UserMilestones");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("WorkoutLogs");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutPlan", b =>
                {
                    b.Navigation("AiGenerations");

                    b.Navigation("WorkoutLogs");

                    b.Navigation("WorkoutPlanExercises");
                });

            modelBuilder.Entity("IntelliFit.Domain.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("TemplateExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
